language: node_js

node_js:
    - "10"

sudo: false

install:
    - npm i
    - npm i semantic-release@15 @semantic-release/npm

script:
    - npm run build
    - npm run test
    - npx semantic-release -e @semantic-release/npm
